@host = http://localhost:8080
@adminAuth = Basic YWRtaW46YWRtaW4=
@userAuth = Basic dXNlcjp1c2Vy
@badAuth = Basic zG9iYTp6bGE=

###
# GET - wszystkie biblioteki
GET {{host}}/webapi/libraries
Accept: application/json

###
# GET - biblioteka po id
GET {{host}}/webapi/libraries/1
Accept: application/json

###
# GET - wszystkie biblioteki (XML)
GET {{host}}/webapi/libraries
Accept: application/xml

###
# GET - biblioteki dla bookId
GET {{host}}/webapi/books/2/libraries
Accept: application/json

###
# GET - ksiazki w bibliotece (libraryId)
GET {{host}}/webapi/libraries/1/books
Accept: application/json

###
# GET - wszystkie ksiazki
GET {{host}}/webapi/books
Accept: application/json

###
# GET - ksiazka po id
GET {{host}}/webapi/books/1
Accept: application/json

###
# GET - wszystkie ksiazki (XML)
GET {{host}}/webapi/books
Accept: application/xml

###
# GET - biblioteki - test ExceptionHandler
GET {{host}}/webapi/libraries?phrase=foo
Accept: application/json

###
# POST - dodanie biblioteki - bez logowania
# oczekiwane: 401
POST {{host}}/webapi/libraries
Content-Type: application/json
Accept: application/json

{
  "name": "Biblioteka Bez Logowania",
  "logo": "https://example.com/logo.png"
}

###
# POST - dodanie biblioteki - user
# oczekiwane: 403
POST {{host}}/webapi/libraries
Authorization: {{userAuth}}
Content-Type: application/json
Accept: application/json

{
  "name": "Biblioteka User",
  "logo": "https://example.com/logo.png"
}
###
# POST - dodanie ksiazki - bez logowania
# oczekiwane: 401
POST {{host}}/webapi/books
Content-Type: application/json
Accept: application/json

{
  "title": "Ksiazka Bez Logowania",
  "cover": "https://example.com/cover.jpg",
  "rating": 4.2,
  "authorId": 1
}

###
# POST - dodanie ksiazki - zly login
# oczekiwane: 401
POST {{host}}/webapi/books
Authorization: {{badAuth}}
Content-Type: application/json
Accept: application/json

{
  "title": "Ksiazka Zly Login",
  "cover": "https://example.com/cover.jpg",
  "rating": 4.2,
  "authorId": 1
}

###
# POST - dodanie ksiazki - user
# oczekiwane: 403
POST {{host}}/webapi/books
Authorization: {{userAuth}}
Content-Type: application/json
Accept: application/json

{
  "title": "Ksiazka User",
  "cover": "https://example.com/cover.jpg",
  "rating": 4.2,
  "authorId": 1
}

###
# POST - dodanie ksiazki - admin
# oczekiwane: sukces
POST {{host}}/webapi/books
Authorization: {{adminAuth}}
Content-Type: application/json
Accept: application/json

{
  "title": "Ksiazka Testowa",
  "cover": "https://example.com/cover.jpg",
  "rating": 4.2,
  "authorId": 1
}

###
# POST - dodanie ksiazki - test rollback/transakcji
# oczekiwane: kontrolowany blad, np. 418
POST {{host}}/webapi/books
Authorization: {{adminAuth}}
Content-Type: application/json
Accept: application/json
Accept-Language: pl

{
  "title": "blad",
  "cover": "https://example.com/cover.jpg",
  "rating": 4.2,
  "authorId": 1
}

###
# POST - dodanie ksiazki - zly authorId
# oczekiwane: blad walidacji / kontrolowany blad
POST {{host}}/webapi/books
Authorization: {{adminAuth}}
Content-Type: application/json
Accept: application/json
Accept-Language: pl

{
  "title": "Nowa Ksiazka",
  "cover": "https://example.com/cover.jpg",
  "rating": 4.2,
  "authorId": 999
}

###
# POST - actuator shutdown
POST {{host}}/actuator/shutdown
Content-Type: application/json
Authorization: {{adminAuth}}
Content-Type: application/json
Accept: application/json

{}